from io import BytesIO
from reportlab.lib.pagesizes import A4
from reportlab.pdfgen import canvas
def generate_pdf(report_slug: str):
    buf = BytesIO()
    c = canvas.Canvas(buf, pagesize=A4)
    c.setTitle(f"{report_slug}.pdf")
    c.drawString(100, 800, f"Report Export: {report_slug}")
    c.drawString(100, 780, "Generated by file-export-service (Celery).")
    c.showPage()
    c.save()
    buf.seek(0)
    return buf
